blueprint:
  name: Sensor Light
  description: >
    Blueprint for Presence Based Lights and Switches Version 0.00.05
    The reason for this blueprint is my old one not being able to handle
      * switches
      * radar based presence detection as
        * presence doesnst flap
        * I was lazy
    
    Still Missing
      * power entity for PIR switches (optional)
      * sun based condition (optional)

  domain: automation
  input:
    trigger_entity:
      name: "Care for the Sun"
      icon: mdi:cog-outline
      collapsed: true
      input:
        include_entity_state:
          name: Use Position of the Sun (Optional)
          description: >
            This option adds triggers and conditions that activate when the specified entity changes its state.
          default: [ "sun_pos_off" ]
          selector:
            select:
              multiple: false
              options:
                - label: "ON"
                  value: "sun_pos_on"
                - label: "OFF"
                  value: "sun_pos_off"

        power_targets:
          name: Power Entities
          description: >
            List of Entities that are to switched on to enable the detection
          default: []
          selector:
            target:
              entity:
                domain: switch
          
        power_offset:
          name: Power Offset
          description: >
            Offset in Minutes for switching on the Detection Power
          default: 5
          selector:
            number:
              min: 0
              max: 15
              step: 0.5
              unit_of_measurement: minutes

    presence_entity:
      name: "Presence Entity"
      description: >
        Still Missing
      selector:
        entity: {}

    timer_entity:
      name: Timer Helper
      description: >
        Timer Entity to be Used for Automation
      selector:
        entity: 
          domain: timer

    light_targets:
      name: "Light Targets"
      description: >
        Light Entities to be Switched when Presence is detected (OPTIONAL)
      selector:
        target:
          entity:
            domain: light
      default: []
      
    switch_targets:
      name: "Switch Targets"
      description: >
        Switch Entities to be Switched when Presence is detected (OPTIONAL)
      selector:
        target:
          entity:
            domain: switch
      default: []

    hold_entity:
      name: "Hold Entity"
      description: >
        Numeric Input Entity to be Used for Initialization of the Timer Entity
        Still Missing
      default: []
      selector:
        entity:
          domain: input_number


mode: parallel
max_exceeded: silent

variables:
  presence_entity: !input 'presence_entity'
  timer_entity: !input 'timer_entity'
  light_targets: !input 'light_targets'
  switch_targets: !input 'switch_targets'
  hold_entity: !input 'hold_entity'
  power_offset: !input 'power_offset'
  power_targets: !input 'power_targets'

  include_entity_state: !input 'include_entity_state'
  
  has_light_targets: "{{ light_targets | length > 0}}"
  has_switch_targets: "{{ switch_targets | length > 0}}"
  has_power_targets: "{{ power_targets | length > 0}}"
  
triggers:
  - trigger: state
    entity_id: !input 'timer_entity'
    to: idle
    id: t_timer_finished
    
  - trigger: state
    entity_id: !input 'presence_entity'
    to: 'on'
    id: t_presence_on
      
  - trigger: state
    entity_id: !input 'presence_entity'
    to: 'off'
    id: t_presence_off


  - trigger: sun
    event: sunrise
    offset: "{{ power_offset * -1.0 }}"
    id: t_sunrise

  - platform: sun
    event: sunset
    offset: "{{ power_offset }}"
    id: t_sunset


condition: []

action:
  - choose:
      - conditions:
        - condition: trigger
          id: t_timer_finished
          alias: "Handle Timer Finished Trigger"
        sequence:
          - if:
              - condition: template
                alias: "check for light targets to turn off"
                value_template: "{{ has_light_targets}}"
            then:
              - action: light.turn_off
                alias: "Turn Off all the Light Targets"
                target: "{{ light_targets }}"

                  
          - if:
              - condition: template
                alias: "check for switch targets to turn off"
                value_template: "{{ has_switch_targets }}"
            then:
              - action: switch.turn_off
                alias: "Turn Off all the Switch Targets"
                target: "{{ switch_targets }}"

      - conditions:
        - condition: and
          - conditions:
              - condition: trigger
                id: t_presence_on
                alias: "Handle Presence On Trigger"

                - condition: or
                  conditions:
                    - condition: template
                      value_template: {{ include_entity_state == 'off' }}
                    - condition: sun
                      before: sunrise
                    - condition: sun
                      after: sunset
        sequence:
          - if:
              - condition: template
                alias: "check for light targets to turn on"
                value_template: "{{ has_light_targets}}"
            then:
              - action: light.turn_on
                alias: "Turn On all the Light Targets"
                target: "{{ light_targets }}"

                  
          - if:
              - alias: "check for Switch targets to turn on"
                condition: template
                value_template: "{{ has_switch_targets }}"
            then:
              - action: switch.turn_on
                alias: "Turn On all the Switche Targets"
                target: "{{ switch_targets }}"
          - action: timer.pause
            target:
              entity_id: "{{ timer_entity }}"
            data:
              duration: '{{ states[hold_entity].state | int }}'

      - conditions:
        - condition: and
          - conditions:
              - condition: trigger
                id: t_presence_off
                alias: "Handle Presence Off Trigger"
              - condition: template
                value_template: '{{ states[timer_entity] == states[hold_entity].state }}'
                
        sequence:
          - action: timer.start
            alias: "Start the Timer"
            target:
              entity_id: "{{ timer_entity }}"
            metadata: {}
            data: {}

      - conditions:
        - condition: and
          conditions:
            - condition: trigger
              id: t_sunset
              alias: "Handle Sunset Trigger"
            - condition: template
              alias: "check for active"
              value_template: "{{ include_entity_state == 'on' }}"
            - condition: template
              alias: "check for Switch targets to turn on"
              value_template: "{{ has_power_targets }}"
        sequence:
          - action: switch.turn_on
            alias: "Turn On Power Switch(es)"
            target: "{{ power_targets }}"
            metadata: {}
            data: {}

      - conditions:
        - condition: and
          conditions:
            - condition: trigger
              id: t_sunrise
              alias: "Handle Sunrise Trigger"
            - condition: template
              alias: "check for active"
              value_template: "{{ include_entity_state == 'on' }}"
            - condition: template
              alias: "check for Switch targets to turn on"
              value_template: "{{ has_power_targets }}"
        sequence:
          - action: switch.turn_off
            alias: "Start the Timer"
            target: "{{ power_targets }}"
            metadata: {}
            data: {}


      - condition: or
        conditions:
        - condition: sun
          before: sunrise
        - condition: sun
          after: sunset

